import com.Q2S.Q2S_Senior_Project.Models.QuarterClass;
import com.Q2S.Q2S_Senior_Project.Models.RulesClass;
import com.Q2S.Q2S_Senior_Project.Models.CourseMapping;
import java.util.Arrays;
global com.Q2S.Q2S_Senior_Project.Models.CourseMapping mapping;
dialect "java"

rule "test rule"
when
    eval ( true )
    //$course: RulesClass(start == "CSC101")
then
    System.out.println("+++++++++++++++++++CSC101 rule fired+++++++++++++++++++++");

    mapping.setMapping("CSC1001 CSC1002");
end
