package rules
import com.Q2S.Q2S_Senior_Project.Models.CourseMapping
import java.util.Arrays
import java.util.List;

rule "Mapping for CSC101"
	when
		courseMapping: CourseMapping(startCourse=="CSC101")
	then
		courseMapping.setMapping(Arrays.asList("CSC1001", "CSC1002"));
	end

rule "Mapping for CSC202"
	when
		courseMapping: CourseMapping(startCourse=="CSC202")
	then
		courseMapping.setMapping(Arrays.asList("CSC2001", "CSC2002"));
	end

rule "Mapping for CSC123"
	when
		courseMapping: CourseMapping(startCourse=="CSC123")
	then
		courseMapping.setMapping(Arrays.asList("CSC1000", "CSC1024"));
	end

rule "Mapping for CSC203"
	when
		courseMapping: CourseMapping(startCourse=="CSC203")
	then
		courseMapping.setMapping(Arrays.asList("CSC1002", "CSC2002"));
	end

rule "Mapping for CSC/CPE357"
	when
		courseMapping: CourseMapping(startCourse=="CSC357" || startCourse=="CPE357")
	then
		courseMapping.setMapping(List.of("CSC2050"));
	end

rule "Mapping for CSC225"
	when
		courseMapping: CourseMapping(startCourse=="CSC225")
	then
		courseMapping.setMapping(List.of("CPE2300"));
	end

rule "Mapping for CSC307"
	when
		courseMapping: CourseMapping(startCourse=="CSC307")
	then
		courseMapping.setMapping(List.of("CSC3100"));
	end

rule "Mapping for CSC430"
	when
		courseMapping: CourseMapping(startCourse=="CSC430")
	then
		courseMapping.setMapping(List.of("CSC3300"));
	end

rule "Mapping for CSC349"
	when
		courseMapping: CourseMapping(startCourse=="CSC349")
	then
		courseMapping.setMapping(List.of("CSC3449"));
	end

rule "Mapping for CSC453"
	when
		courseMapping: CourseMapping(startCourse=="CSC453")
	then
		courseMapping.setMapping(List.of("CSC4553"));
	end

rule "Mapping for CSC365"
	when
		courseMapping: CourseMapping(startCourse=="CSC365")
	then
		courseMapping.setMapping(List.of("CSC3665"));
	end

rule "Mapping for CSC445"
	when
		courseMapping: CourseMapping(startCourse=="CSC445")
	then
		courseMapping.setMapping(List.of("CSC3445"));
	end

rule "Mapping for CSC308 or CSC309"
	when
		courseMapping: CourseMapping(startCourse=="CSC308" || startCourse=="CSC309")
	then
		courseMapping.setMapping(List.of("CSC3100"));
	end

rule "Mapping for CSC321 or CSC323 or CSC325"
	when
		courseMapping: CourseMapping(startCourse=="CSC321" || startCourse=="CSC323" || startCourse=="CSC325")
	then
		courseMapping.setMapping(List.of("CSC3201"));
	end