package rules
import com.Q2S.Q2S_Senior_Project.Models.CourseMapping
import java.util.Arrays;

rule "Mapping for CSC101"
	when
		productObject: CourseMapping(startCourse=="CSC101")
	then
		productObject.setMapping(Arrays.asList("CSC1001", "CSC1002"));
	end

rule "Mapping for CSC202"
	when
		productObject: CourseMapping(startCourse=="CSC202")
	then
		productObject.setMapping(Arrays.asList("CSC2001", "CSC2002"));
	end

rule "Mapping for CSC123"
	when
		productObject: CourseMapping(startCourse=="CSC123")
	then
		productObject.setMapping(Arrays.asList("CSC1000", "CSC1024"));
	end

rule "Mapping for CSC203"
	when
		productObject: CourseMapping(startCourse=="CSC203")
	then
		productObject.setMapping(Arrays.asList("CSC1002", "CSC2002"));
	end

rule "Mapping for CSC/CPE357"
	when
		productObject: CourseMapping(startCourse=="CSC357" || startCourse=="CPE357")
	then
		productObject.setMapping(Arrays.asList("CSC2050"));
	end

rule "Mapping for CSC225"
	when
		productObject: CourseMapping(startCourse=="CSC225")
	then
		productObject.setMapping(Arrays.asList("CPE2300"));
	end