import java.util.List;
import java.util.Arrays;
import com.Q2S.Q2S_Senior_Project.Models.Requirement;

rule "CSC101 Requirement"
when
    req: Requirement(courses != null)
then
    req.setMet(req.getCourses().contains("CSC101"));
end

rule "Life Science Elective"
when
    req: Requirement(courses != null)
then
    req.setMet(req.getCourses().contains("BIO111") ||
                req.getCourses().contains("BIO161") ||
                req.getCourses().contains("BOT121") ||
                req.getCourses().contains("MCRO221") ||
                req.getCourses().contains("MCRO224") ||
                (req.getCourses().contains("BIO213") && req.getCourses().contains("BMED213")));
end

rule "Math Elective"
when
    req: Requirement(courses != null)
then
    req.setMet(req.getCourses().contains("MATH248") ||
                    req.getCourses().contains("MATH304") ||
                    req.getCourses().contains("MATH335") ||
                    req.getCourses().contains("MATH336") ||
                    req.getCourses().contains("MATH451"));
end



rule "Check all requirements"
salience -1
when
    // Count the number of met requirements
    $count: Number(intValue >= 1) from accumulate(
        Boolean(),
        count()
    )
    // Count the total number of requirements
    $total: Number(intValue > 0) from accumulate(
        $r: Boolean(),
        count($r)
    )
    // Ensure all requirements are met
    eval($count == $total)
then
    System.out.println("All requirements are met!");
end



//for degree requirements, have "validate" button to check if all met
// at the time of validate -- map all to graduating catalog so don't ahve to requirement map
//do course mappings dynamically
//go through courses and compare against each requirement

//figure out ands/ors
// need to populate database to test
//flowchart (list of classes) will be input to SE rules
// each rule is a requirement


